添加Hibernate，测试失败
1. Maven Install 时，运行测试单元，失败。
信息如下：
Tests in error:
testSaveMethod(me.gacl.test.TestHibernate): Error creating bean with
name 'userDao': Injection of autowired dependencies failed; nested
exception is org.springframework.beans.factory.BeanCreationException:
Could not autowire field: private org.hibernate.SessionFactory
me.gacl.dao.impl.UserDaoImpl.sessionFactory; nested exception is
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'sessionFactory' defined in class path resource
[spring-hibernate.xml]: Cannot resolve reference to bean 'dataSource'
while setting bean property 'dataSource'; nested exception is
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'dataSource' defined in class path resource
[spring-hibernate.xml]: Error setting property values; nested exception
is org.springframework.beans.PropertyBatchUpdateException; nested
PropertyAccessExceptions (1) are:
test(me.gacl.test.TestSpring): Error creating bean with name 'userDao':
Injection of autowired dependencies failed; nested exception is
org.springframework.beans.factory.BeanCreationException: Could not
autowire field: private org.hibernate.SessionFactory
me.gacl.dao.impl.UserDaoImpl.sessionFactory; nested exception is
org.springframework.beans.factory.NoSuchBeanDefinitionException: No
matching bean of type [org.hibernate.SessionFactory] found for
dependency: expected at least 1 bean which qualifies as autowire
candidate for this dependency. Dependency annotations:
{@org.springframework.beans.factory.annotation.Autowired(required=true)}